name: Performance Test Run

on:
  push:
    branches:
      - main

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install required tools and Python
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk
        sudo apt-get install -y jmeter
        sudo apt-get install -y python3-pip
        pip3 install taurus
        sudo apt-get install -y chromium-browser # Install headless browser (e.g., Chrome)

    - name: Run JMeter test using Taurus
      id: taurus
      run: |
        bzt jmeter/tests/performance/9MAYPROD-SF-NOcookAndClariity.jmx -report

    - name: Export Report Link
      run: |
        report_link=$(grep -oP 'https:\/\/a\.blazemeter\.com\/app\/\?public-token=\S+' <<< "${{ steps.taurus.outputs.stdout }}")
        echo "::set-output name=report_link::$report_link"

    - name: Conditional Steps
      run: |
        if [[ "${{ steps.taurus.outputs.stdout }}" == *"bzt"* ]]; then
          # Taurus test execution, export report link
          report_link=$(grep -oP 'https:\/\/a\.blazemeter\.com\/app\/\?public-token=\S+' <<< "${{ steps.taurus.outputs.stdout }}")
          echo "::set-output name=report_link::$report_link"
        else
          # JMeter test execution, archive and generate HTML reports
          ./scripts/archive_reports.sh
          ./scripts/generate_reports.sh
        fi

    - name: Set version
      env:
        VERSION: ${{ github.sha }}
      run: |
        echo "Version: $VERSION" > version.txt

    - name: Commit version
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add version.txt
        git commit -m "Update version"
        git push origin main
