name: Performance Test Run
on:
  push:
    branches:
      - main
jobs:
  jmeter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Check for changes in commits
      id: git_changes
      run: |
        git fetch --depth=1 origin $GITHUB_SHA
        CHANGES=$(git diff --name-only $GITHUB_SHA...origin/main)
        echo "::set-output name=changes::$CHANGES"
      shell: bash
    - name: Install required tools
      if: steps.git_changes.outputs.changes != ''
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk
        sudo apt-get install -y jmeter
        sudo apt-get install -y python3 python3-pip
        sudo apt-get install -y chromium-browser
    - name: Install Taurus
      if: steps.git_changes.outputs.changes != '' && steps.taurus.outputs.stdout == ''
      run: |
        pip3 install bzt
        echo "export PATH=$HOME/.local/bin:\$PATH" >> $GITHUB_ENV
    - name: Refresh environment variables
      run: |
        source $GITHUB_ENV
        sleep 30
    - name: Verify Taurus installation
      run: |
        bzt -h
      shell: bash
    - name: Run JMeter test using Taurus
      id: taurus
      run: |
        bzt jmeter/tests/performance/9MAYPROD-SF-NOcookAndClariity.jmx -report
    - name: Conditional Steps
      run: |
        if [[ "${{ steps.taurus.outputs.stdout }}" == *"bzt"* ]]; then
          report_link=$(grep -oP 'https:\/\/a\.blazemeter\.com\/app\/\?public-token=\S+' <<< "${{ steps.taurus.outputs.stdout }}")
          echo "::set-output name=report_link::$report_link"
          echo "# $(date '+%Y-%m-%d_%H-%M-%S') - $report_link" >> reports.txt
        else
          ./scripts/archive_reports.sh
          ./scripts/generate_reports.sh
        fi
    - name: Set version
      env:
        VERSION: ${{ github.sha }}
      run: |
        echo "Version: $VERSION" > version.txt
    - name: Commit version
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add version.txt reports.txt
        git commit -m "Update version and add report link"
        git push origin main
