name: Performance Test Run

on:
  push:
    branches:
      - main

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk
        sudo apt-get install -y jmeter
        sudo apt-get install -y python3 python3-pip
        sudo apt-get install -y chromium-browser

    - name: Install Taurus
      run: |
        if ! command -v bzt &> /dev/null; then
          pip3 install bzt
          echo "export PATH=$HOME/.local/bin:\$PATH" >> $GITHUB_ENV
        fi

    - name: Refresh environment variables
      run: |
        source $GITHUB_ENV
        sleep 30

    - name: Verify Taurus installation
      run: |
        bzt -h
      shell: bash

    - name: Run JMeter test using Taurus
      id: taurus
      run: |
        bzt jmeter/tests/performance/9MAYPROD-SF-NOcookAndClariity.jmx -report | tee output.log

    - name: Export Report Link and Timestamp
      id: export-report-link
      run: |
        report_link=$(grep -oP 'https:\/\/a\.blazemeter\.com\/app\/\?public-token=\S+' output.log)
        timestamp=$(date '+%d_%m_%Y_%H_%M')
        echo "report_link=$report_link" >> $GITHUB_ENV
        echo "timestamp=$timestamp" >> $GITHUB_ENV

    - name: Conditional Steps
      if: ${{ env.report_link }}
      run: |
        report_link="${{ env.report_link }}"
        timestamp="${{ env.timestamp }}"
        report_filename="report_${timestamp}.txt"
        echo "# $timestamp - $report_link" > $report_filename
        echo "# Report Link - ${timestamp}" > report_link_${timestamp}.md
        echo "The report is available here: [Report Link]($report_link)" >> report_link_${timestamp}.md
        sleep 5
        chmod +x ./scripts/archive_reports.sh
        sleep 5
        ./scripts/archive_reports.sh
        sleep 5
        chmod +x ./scripts/generate_reports.sh
        sleep 5
        ./scripts/generate_reports.sh
        sleep 5

    - name: Upload Report File as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: report-file
        path: report_${{ env.timestamp }}.txt

    - name: Create Summary with Report Link
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          const timestamp = new Date().toISOString().replace(/:/g, '-');
          const summaryPath = path.join(process.env.GITHUB_WORKSPACE, `report_link_${timestamp}.md`);
          if (fs.existsSync(summaryPath)) {
            const summaryContent = fs.readFileSync(summaryPath, 'utf8');
            const { data: checkRuns } = await octokit.rest.checks.listForRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: context.runId
            });
            const checkRunId = checkRuns.check_runs[0].id;
            await octokit.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: checkRunId,
              output: {
                title: 'Report Summary',
                summary: summaryContent
              }
            });
          }

    - name: Set version
      env:
        VERSION: ${{ github.sha }}
      run: |
        echo "Version: $VERSION" > version.txt

    - name: Commit version
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git remote set-url origin https://github.com/${{ github.repository }}
        git add version.txt
        git commit -m "Update version"
        git push origin main
