name: Performance Test Run

on:
  push:
    branches:
      - main

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install required tools
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk
        sudo apt-get install -y jmeter
        sudo apt-get install -y python3 python3-pip

    - name: Install Taurus
      run: |
        if ! command -v bzt &> /dev/null
        then
          pip3 install bzt
          echo "export PATH=$HOME/.local/bin:\$PATH" >> $GITHUB_ENV
        fi

    - name: Refresh environment variables
      run: |
        source $GITHUB_ENV
        sleep 30  # Wait for 30 seconds to ensure the environment variables are properly sourced

    - name: Verify Taurus installation
      run: |
        bzt -h  # Use bzt -h instead of bzt --version to verify installation
      shell: bash

    - name: Run JMeter test using Taurus
      run: |
        bzt awsTaurus/jmeter/tests/performance/9MAYPROD-SF-NOcookAndClariity.jmx -report

    - name: Archive JMeter reports
      run: |
        ./scripts/archive_reports.sh

    - name: Generate HTML reports
      run: |
        ./scripts/generate_reports.sh

    - name: Set version
      env:
        VERSION: ${{ github.sha }}
      run: |
        echo "Version: $VERSION" > version.txt

    - name: Commit version
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add version.txt
        git commit -m "Update version"
        git push origin main
