name: Performance Test Run

on:
  push:
    branches:
      - main

jobs:
  jmeter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install required tools
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk jmeter python3 python3-pip chromium-browser

      - name: Install Taurus
        run: |
          pip3 install bzt

      - name: Run JMeter test using Taurus
        id: taurus
        run: |
          bzt jmeter/tests/performance/9MAYPROD-SF-NOcookAndClariity.jmx -report

      - name: Extract Online Report URL
        id: extract-url
        run: |
          report_link=$(grep -oP 'https://a\.blazemeter\.com/app/\?public-token=\S+' <<< "${{ steps.taurus.outputs.stdout }}")
          echo $report_link > report_url.txt

      - name: Upload Report URL as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: report-url
          path: report_url.txt

      - name: Set version
        env:
          VERSION: ${{ github.sha }}
        run: |
          echo "Version: $VERSION" > version.txt

      - name: Commit version
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add version.txt
          git commit -m "Update version"
          git push origin main
